name: ffd
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=2.1
  - pandas=2.2
  - matplotlib
  - seaborn=0.13
  - shapely
  - scipy
  - tqdm
  - ca-certificates
  - openssl
  - ipython
  - certifi
  - jupyter
  - pytables
  - ipykernel
  - ipympl
  - typer
  - natsort
