"""
This script detects the onset of a signal response after stimulation and computes the relative delay for each trial and animal.

Specify each entry, reading carefully what they do, then run the script with the 'ffd' conda environment activated.

It uses the `features.csv` file generated by `features-from-dlc`.

How to use the script:

1. Replace with the full path to your `features.csv` file.
2. Replace with the full path to the directory where figures will be saved.
3. Replace with the exact column (feature) name from the csv file you want to analyse.
4. Map each condition to its animal.
5. Run script

"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# ------------------------------------------------------------------
#                           Parameters
# ------------------------------------------------------------------

CSV_FILE = r"D:\path\to\features.csv"
OUTPUT_SUMMARY_CSV = r"D:\path\to\save\directory"

# Column to analyze
SIGNAL_COL = "deflection left"
# Calculation parameters
MAX_TIME_MS = 40
# Criteria 1: threshold computation
PERCENTILE = 99.5
# Criteria 2: amplitude computation
USE_DELTA = True
DELTA = 1
# Criteria 3
MIN_CONSECUTIVE = 3

# Animals per condition
CONDITIONS = {
    "condition1": ["animal0"],
    "condition2": ["something"],
    "condition3": ["something_else"],
}

# Display parameter
JITTER = 0.08

# ------------------------------------------------------------------
#                           Loading data
# ------------------------------------------------------------------

df = pd.read_csv(CSV_FILE)
df.columns = df.columns.str.strip()

if SIGNAL_COL not in df.columns:
    raise ValueError(
        f"Column '{SIGNAL_COL}' not found.\n"
        f"Available columns: {df.columns.tolist ()}"
    )

ALL_ANIMALS = [a for animals in CONDITIONS.values() for a in animals]
CONDITION_ORDER = list(CONDITIONS.keys())
X_POS = {cond: i for i, cond in enumerate(CONDITION_ORDER)}

def assign_condition(animal):
    for cond, animals in CONDITIONS.items():
        if animal in animals:
            return cond
    return np.nan

# ------------------------------------------------------------------
#                       Delay computation
# ------------------------------------------------------------------

rows = []
for (animal, trialID), dft in df.groupby(["animal", "trialID"]):

    if animal not in ALL_ANIMALS:
        continue

    dft = dft.sort_values("time").reset_index(drop=True)

    base_mask = dft["time"] < 0
    if base_mask.sum() < 5:
        rows.append({"animal": animal, "trialID": trialID, "delay_rel_ms": np.nan})
        continue

    sig = dft[SIGNAL_COL].to_numpy()
    tm = dft["time"].to_numpy()
    vel = np.abs(np.gradient(sig, tm))

    baseline_mean = sig[base_mask].mean()

    # amplitude threshold only if requested
    if USE_DELTA:
        amp_threshold = baseline_mean + DELTA

    joint_baseline = np.abs(sig[base_mask]) * vel[base_mask]
    stat_threshold = np.percentile(joint_baseline, PERCENTILE)

    pos_idx = dft.index[dft["time"] > 0]
    if len(pos_idx) == 0:
        rows.append({"animal": animal, "trialID": trialID, "delay_rel_ms": np.nan})
        continue

    t0 = tm[pos_idx[0]]

    t_cross = np.nan
    for i in range(pos_idx[0] + 1, len(dft) - (MIN_CONSECUTIVE - 1)):
        joint_vals = np.abs(sig[i:i + MIN_CONSECUTIVE]) * vel[i:i + MIN_CONSECUTIVE]

        if USE_DELTA:
            amp_vals = sig[i:i + MIN_CONSECUTIVE]
            cond = np.all(joint_vals > stat_threshold) and np.all(amp_vals > amp_threshold)
        else:
            cond = np.all(joint_vals > stat_threshold)

        if cond:
            t_cross = tm[i]
            break

    if np.isnan(t_cross):
        rows.append({"animal": animal, "trialID": trialID, "delay_rel_ms": np.nan})
        continue

    delay_rel_ms = (t_cross - t0) * 1000
    if delay_rel_ms > MAX_TIME_MS:
        delay_rel_ms = np.nan

    rows.append({
        "animal": animal,
        "trialID": trialID,
        "delay_rel_ms": delay_rel_ms
    })

delay_df = pd.DataFrame(rows)

# ------------------------------------------------------------------
#                       Stats by animal
# ------------------------------------------------------------------

animal_stats = (
    delay_df
    .groupby("animal")
    .agg(
        mean_delay_rel_ms=("delay_rel_ms", "mean"),
        n_trials=("delay_rel_ms", "size"),
        n_crossings=("delay_rel_ms", lambda x: x.notna().sum())
    )
    .reindex(ALL_ANIMALS)
    .reset_index()
)

animal_stats["n_trials"] = animal_stats["n_trials"].fillna(0).astype(int)
animal_stats["n_crossings"] = animal_stats["n_crossings"].fillna(0).astype(int)

animal_stats["percent_crossing"] = np.where(
    animal_stats["n_trials"] > 0,
    100 * animal_stats["n_crossings"] / animal_stats["n_trials"],
    0
)

animal_stats["condition"] = animal_stats["animal"].apply(assign_condition)
animal_stats["mean_delay_plot_ms"] = animal_stats["mean_delay_rel_ms"].fillna(MAX_TIME_MS)

# ------------------------------------------------------------------
#                           Export CSV
# ------------------------------------------------------------------

animal_stats.assign(
    signal=SIGNAL_COL,
    percentile=PERCENTILE,
    use_delta=USE_DELTA,
    delta=DELTA if USE_DELTA else np.nan,
    min_consecutive=MIN_CONSECUTIVE,
    max_time_ms=MAX_TIME_MS
).to_csv(OUTPUT_SUMMARY_CSV, index=False)

print("CSV saved:", os.path.abspath(OUTPUT_SUMMARY_CSV))

# ------------------------------------------------------------------
#                       Stats by condition
# ------------------------------------------------------------------

valid_delay = animal_stats.dropna(subset=["mean_delay_rel_ms"])

summary_delay = (
    valid_delay
    .groupby("condition")["mean_delay_rel_ms"]
    .agg(
        mean_delay="mean",
        sem_delay=lambda x: x.std(ddof=1) / np.sqrt(len(x)) if len(x) > 1 else 0
    )
    .reindex(CONDITION_ORDER)
    .reset_index()
)

summary_percent = (
    animal_stats
    .groupby("condition")["percent_crossing"]
    .agg(
        mean_percent="mean",
        sem_percent=lambda x: x.std(ddof=1) / np.sqrt(len(x)) if len(x) > 1 else 0
    )
    .reindex(CONDITION_ORDER)
    .reset_index()
)

# ------------------------------------------------------------------
#                       Plot Delay
# ------------------------------------------------------------------

plt.figure(figsize=(4, 6))
plt.bar(summary_delay["condition"], summary_delay["mean_delay"],
        yerr=summary_delay["sem_delay"], capsize=6)

for _, row in animal_stats.iterrows():
    if pd.isna(row["condition"]):
        continue
    x = X_POS[row["condition"]] + np.random.uniform(-JITTER, JITTER)
    plt.scatter(x, row["mean_delay_plot_ms"], zorder=3)

plt.ylabel("Relative delay (ms)")
plt.title(f"{SIGNAL_COL} - delay (perc {PERCENTILE}, delta={USE_DELTA})")
plt.ylim(0, 50)
plt.tight_layout()
plt.show()

# ------------------------------------------------------------------
#                       Plot crossing rate
# ------------------------------------------------------------------

plt.figure(figsize=(4, 6))
plt.bar(summary_percent["condition"], summary_percent["mean_percent"],
        yerr=summary_percent["sem_percent"], capsize=6)

for _, row in animal_stats.iterrows():
    if pd.isna(row["condition"]):
        continue
    x = X_POS[row["condition"]] + np.random.uniform(-JITTER, JITTER)
    plt.scatter(x, row["percent_crossing"], zorder=3)

plt.ylabel("Valid crossings (%)")
plt.title(f"{SIGNAL_COL} - % crossings (perc {PERCENTILE}, delta={USE_DELTA})")
plt.ylim(0, 100)
plt.tight_layout()
plt.show()